version : '3.1'
services:
  minio:
    image: minio/minio
    container_name: minIo
    environment:
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_ACCESS_KEY=Naveen@123
      - MINIO_SECRET_KEY=Naveen@123
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
    command: server /data
    restart: always


